#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AbnormalRender_Frozen_EspeciallyBig

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AbnormalRender_Frozen_EspeciallyBig.AbnormalRender_Frozen_EspeciallyBig_C
// 0x0000 (0x02A0 - 0x02A0)
class UAbnormalRender_Frozen_EspeciallyBig_C final : public UCharacterAbnormalRenderState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AbnormalRender_Frozen_EspeciallyBig_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AbnormalRender_Frozen_EspeciallyBig_C")
	}
	static class UAbnormalRender_Frozen_EspeciallyBig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbnormalRender_Frozen_EspeciallyBig_C>();
	}
};
DUMPER7_ASSERTS_UAbnormalRender_Frozen_EspeciallyBig_C;

}

