#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Mon_108_Main

#include "Basic.hpp"

#include "ABP_Mon_108_Main_classes.hpp"
#include "ABP_Mon_108_Main_parameters.hpp"


namespace SDK
{

// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.ExecuteUbergraph_ABP_Mon_108_Main
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Mon_108_Main_C::ExecuteUbergraph_ABP_Mon_108_Main(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "ExecuteUbergraph_ABP_Mon_108_Main");

	Params::ABP_Mon_108_Main_C_ExecuteUbergraph_ABP_Mon_108_Main Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Mon_108_Main_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "BlueprintUpdateAnimation");

	Params::ABP_Mon_108_Main_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_1968BF77400B0B0D0580ED8720B7554F
// (BlueprintEvent)

void UABP_Mon_108_Main_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_1968BF77400B0B0D0580ED8720B7554F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_1968BF77400B0B0D0580ED8720B7554F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_BCFB5D784A913E1B765BDFA942D92D44
// (BlueprintEvent)

void UABP_Mon_108_Main_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_BCFB5D784A913E1B765BDFA942D92D44()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_BCFB5D784A913E1B765BDFA942D92D44");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_16938E7B4A1FFD05C5EC2EB094E307A3
// (BlueprintEvent)

void UABP_Mon_108_Main_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_16938E7B4A1FFD05C5EC2EB094E307A3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_16938E7B4A1FFD05C5EC2EB094E307A3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_FA3ECF6E45F9E885E79A92A8B3324D19
// (BlueprintEvent)

void UABP_Mon_108_Main_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_FA3ECF6E45F9E885E79A92A8B3324D19()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_TransitionResult_FA3ECF6E45F9E885E79A92A8B3324D19");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_SequencePlayer_758AC1F04908565ECDE1D3818C48318F
// (BlueprintEvent)

void UABP_Mon_108_Main_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_SequencePlayer_758AC1F04908565ECDE1D3818C48318F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_108_Main_AnimGraphNode_SequencePlayer_758AC1F04908565ECDE1D3818C48318F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Mon_108_Main_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "AnimGraph");

	Params::ABP_Mon_108_Main_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.GroundIKLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        GroundIkInputPose                                      (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        GroundIKLayer_0                                        (Parm, OutParm, NoDestructor)

void UABP_Mon_108_Main_C::GroundIKLayer(const struct FPoseLink& GroundIkInputPose, struct FPoseLink* GroundIKLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "GroundIKLayer");

	Params::ABP_Mon_108_Main_C_GroundIKLayer Parms{};

	Parms.GroundIkInputPose = std::move(GroundIkInputPose);

	UObject::ProcessEvent(Func, &Parms);

	if (GroundIKLayer_0 != nullptr)
		*GroundIKLayer_0 = std::move(Parms.GroundIKLayer_0);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.CurveDataLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        CurveInputPose                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        CurveDataLayer_0                                       (Parm, OutParm, NoDestructor)

void UABP_Mon_108_Main_C::CurveDataLayer(const struct FPoseLink& CurveInputPose, struct FPoseLink* CurveDataLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "CurveDataLayer");

	Params::ABP_Mon_108_Main_C_CurveDataLayer Parms{};

	Parms.CurveInputPose = std::move(CurveInputPose);

	UObject::ProcessEvent(Func, &Parms);

	if (CurveDataLayer_0 != nullptr)
		*CurveDataLayer_0 = std::move(Parms.CurveDataLayer_0);
}


// Function ABP_Mon_108_Main.ABP_Mon_108_Main_C.HitAddtiveLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        HitInputPose                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        HitAddtiveLayer_0                                      (Parm, OutParm, NoDestructor)

void UABP_Mon_108_Main_C::HitAddtiveLayer(const struct FPoseLink& HitInputPose, struct FPoseLink* HitAddtiveLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Mon_108_Main_C", "HitAddtiveLayer");

	Params::ABP_Mon_108_Main_C_HitAddtiveLayer Parms{};

	Parms.HitInputPose = std::move(HitInputPose);

	UObject::ProcessEvent(Func, &Parms);

	if (HitAddtiveLayer_0 != nullptr)
		*HitAddtiveLayer_0 = std::move(Parms.HitAddtiveLayer_0);
}

}

