#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AICondition_GeTeamCaptaintIsModiferExist

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AICondition_GeTeamCaptaintIsModiferExist.AICondition_GeTeamCaptaintIsModiferExist_C
// 0x0008 (0x0030 - 0x0028)
class UAICondition_GeTeamCaptaintIsModiferExist_C final : public UAICondition_BlueprintLogic
{
public:
	int32                                         ID;                                                // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool PerformanceCheck(const class AGameCharacter* Who);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AICondition_GeTeamCaptaintIsModiferExist_C">();
	}
	static class UAICondition_GeTeamCaptaintIsModiferExist_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAICondition_GeTeamCaptaintIsModiferExist_C>();
	}
};
static_assert(alignof(UAICondition_GeTeamCaptaintIsModiferExist_C) == 0x000008, "Wrong alignment on UAICondition_GeTeamCaptaintIsModiferExist_C");
static_assert(sizeof(UAICondition_GeTeamCaptaintIsModiferExist_C) == 0x000030, "Wrong size on UAICondition_GeTeamCaptaintIsModiferExist_C");
static_assert(offsetof(UAICondition_GeTeamCaptaintIsModiferExist_C, ID) == 0x000028, "Member 'UAICondition_GeTeamCaptaintIsModiferExist_C::ID' has a wrong offset!");

}

