#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BaseSummon

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BaseSummon.BaseSummon_C
// 0x0010 (0x1430 - 0x1420)
#pragma pack(push, 0x1)
class alignas(0x10) ABaseSummon_C : public AGameSummon
{
public:
	class UAnimMontage*                           Celebrate_Montage;                                 // 0x1420(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	float Abnormal_RepelAnimTime(int32 AnimType, bool bIsBack);
	float Abnormal_LieDownAnimTime(int32 AnimType);
	float Abnormal_GetUpAnimTime(int32 AnimType);
	void SetMeshTransSortPriority(int32 NewSort);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BaseSummon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BaseSummon_C")
	}
	static class ABaseSummon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABaseSummon_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ABaseSummon_C;

}

