#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wp81501

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WeaponBase_Bow_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Wp81501.BP_Wp81501_C
// 0x0020 (0x1E80 - 0x1E60)
class ABP_Wp81501_C final : public AWeaponBase_Bow_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Wp81501_C;                       // 0x1E60(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      e_wp08a_a001c_p;                                   // 0x1E68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Arrow;                                             // 0x1E70(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_BP_Wp81501(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Wp81501_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Wp81501_C")
	}
	static class ABP_Wp81501_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Wp81501_C>();
	}
};
DUMPER7_ASSERTS_ABP_Wp81501_C;

}

