#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BulletScreen_400601

#include "Basic.hpp"

#include "BulletScreen_400601_classes.hpp"
#include "BulletScreen_400601_parameters.hpp"


namespace SDK
{

// Function BulletScreen_400601.BulletScreen_400601_C.GetTargetLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Loc                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABulletScreen_400601_C::GetTargetLocation(struct FVector* Loc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletScreen_400601_C", "GetTargetLocation");

	Params::BulletScreen_400601_C_GetTargetLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Loc != nullptr)
		*Loc = std::move(Parms.Loc);
}


// Function BulletScreen_400601.BulletScreen_400601_C.CalGenrateLocation&&Roation
// (BlueprintCallable, BlueprintEvent)

void ABulletScreen_400601_C::CalGenrateLocation__Roation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletScreen_400601_C", "CalGenrateLocation&&Roation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BulletScreen_400601.BulletScreen_400601_C.GenerateBullet
// (BlueprintCallable, BlueprintEvent)

void ABulletScreen_400601_C::GenerateBullet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletScreen_400601_C", "GenerateBullet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BulletScreen_400601.BulletScreen_400601_C.ExecuteUbergraph_BulletScreen_400601
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABulletScreen_400601_C::ExecuteUbergraph_BulletScreen_400601(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletScreen_400601_C", "ExecuteUbergraph_BulletScreen_400601");

	Params::BulletScreen_400601_C_ExecuteUbergraph_BulletScreen_400601 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BulletScreen_400601.BulletScreen_400601_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABulletScreen_400601_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletScreen_400601_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// LuaFunction BulletScreen_400601.BulletScreen_400601_C.OnCalcBulletLocAndRot
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void ABulletScreen_400601_C::OnCalcBulletLocAndRot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletScreen_400601_C", "OnCalcBulletLocAndRot");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BulletScreen_400601.BulletScreen_400601_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABulletScreen_400601_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletScreen_400601_C", "GetModuleName");

	Params::BulletScreen_400601_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

