#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageEffect_TargetModifierID

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DamageEffect_TargetModifierID.DamageEffect_TargetModifierID_C
// 0x0000 (0x0138 - 0x0138)
class UDamageEffect_TargetModifierID_C final : public UCastConditionCheck_DamageEffect_TargetModifierID
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DamageEffect_TargetModifierID_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DamageEffect_TargetModifierID_C")
	}
	static class UDamageEffect_TargetModifierID_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDamageEffect_TargetModifierID_C>();
	}
};
DUMPER7_ASSERTS_UDamageEffect_TargetModifierID_C;

}

