#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Fight_npc_hpnpbreak

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass fight_npc_hpnpbreak.fight_npc_hpnpbreak_C
// 0x0000 (0x0600 - 0x0600)
class UFight_npc_hpnpbreak_C final : public UHPComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"fight_npc_hpnpbreak_C">();
	}
	static class UFight_npc_hpnpbreak_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFight_npc_hpnpbreak_C>();
	}
};
static_assert(alignof(UFight_npc_hpnpbreak_C) == 0x000010, "Wrong alignment on UFight_npc_hpnpbreak_C");
static_assert(sizeof(UFight_npc_hpnpbreak_C) == 0x000600, "Wrong size on UFight_npc_hpnpbreak_C");

}

