#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: fight_scene

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass fight_scene.fight_scene_C
// 0x0000 (0x0240 - 0x0240)
class Ufight_scene_C final : public UGameNiagaraSystemWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("fight_scene_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"fight_scene_C")
	}
	static class Ufight_scene_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ufight_scene_C>();
	}
};
DUMPER7_ASSERTS_Ufight_scene_C;

}

