#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Monster_lock_component

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass monster_lock_component.monster_lock_component_C
// 0x0000 (0x05D0 - 0x05D0)
class UMonster_lock_component_C final : public UTipComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"monster_lock_component_C">();
	}
	static class UMonster_lock_component_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMonster_lock_component_C>();
	}
};
static_assert(alignof(UMonster_lock_component_C) == 0x000010, "Wrong alignment on UMonster_lock_component_C");
static_assert(sizeof(UMonster_lock_component_C) == 0x0005D0, "Wrong size on UMonster_lock_component_C");

}

