#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Postswitch_scene

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass postswitch_scene.postswitch_scene_C
// 0x0000 (0x0100 - 0x0100)
class UPostswitch_scene_C final : public UPostProcessMaterialParams
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"postswitch_scene_C">();
	}
	static class UPostswitch_scene_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPostswitch_scene_C>();
	}
};
static_assert(alignof(UPostswitch_scene_C) == 0x000008, "Wrong alignment on UPostswitch_scene_C");
static_assert(sizeof(UPostswitch_scene_C) == 0x000100, "Wrong size on UPostswitch_scene_C");

}

