#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_31

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_31.RandomBuff_31_C
// 0x0000 (0x0148 - 0x0148)
class URandomBuff_31_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RandomBuff_31_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RandomBuff_31_C")
	}
	static class URandomBuff_31_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_31_C>();
	}
};
DUMPER7_ASSERTS_URandomBuff_31_C;

}

