#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_130

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_130.RandomBuff_130_C
// 0x0000 (0x0150 - 0x0150)
class URandomBuff_130_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RandomBuff_130_C">();
	}
	static class URandomBuff_130_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_130_C>();
	}
};
static_assert(alignof(URandomBuff_130_C) == 0x000008, "Wrong alignment on URandomBuff_130_C");
static_assert(sizeof(URandomBuff_130_C) == 0x000150, "Wrong size on URandomBuff_130_C");

}

