#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_113

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_113.RandomBuff_113_C
// 0x0000 (0x0150 - 0x0150)
class URandomBuff_113_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RandomBuff_113_C">();
	}
	static class URandomBuff_113_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_113_C>();
	}
};
static_assert(alignof(URandomBuff_113_C) == 0x000008, "Wrong alignment on URandomBuff_113_C");
static_assert(sizeof(URandomBuff_113_C) == 0x000150, "Wrong size on URandomBuff_113_C");

}

