#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_64

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_64.RandomBuff_64_C
// 0x0000 (0x0150 - 0x0150)
class URandomBuff_64_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RandomBuff_64_C">();
	}
	static class URandomBuff_64_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_64_C>();
	}
};
static_assert(alignof(URandomBuff_64_C) == 0x000008, "Wrong alignment on URandomBuff_64_C");
static_assert(sizeof(URandomBuff_64_C) == 0x000150, "Wrong size on URandomBuff_64_C");

}

