#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ReturnDamageEffectDamageValue

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ReturnDamageEffectDamageValue.ReturnDamageEffectDamageValue_C
// 0x0000 (0x0028 - 0x0028)
class UReturnDamageEffectDamageValue_C final : public UCalcAttributeSpecialFunction
{
public:
	float CaclValue(const class UAbilityComponentBase* InLauncher, const class UAbilityComponentBase* InTarget, const TArray<struct FParamInfo>& Params_0, const struct FPreDamageResultData& PreDamageData, int32 InSkillLevel, const class UModifier* InModifier) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ReturnDamageEffectDamageValue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ReturnDamageEffectDamageValue_C")
	}
	static class UReturnDamageEffectDamageValue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReturnDamageEffectDamageValue_C>();
	}
};
DUMPER7_ASSERTS_UReturnDamageEffectDamageValue_C;

}

