#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ReturnAttributeProductValue

#include "Basic.hpp"

#include "ReturnAttributeProductValue_classes.hpp"
#include "ReturnAttributeProductValue_parameters.hpp"


namespace SDK
{

// Function ReturnAttributeProductValue.ReturnAttributeProductValue_C.CaclValue
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class UAbilityComponentBase*      InLauncher                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAbilityComponentBase*      InTarget                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<struct FParamInfo>&        Params_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FPreDamageResultData&      PreDamageData                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// int32                                   InSkillLevel                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UModifier*                  InModifier                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UReturnAttributeProductValue_C::CaclValue(const class UAbilityComponentBase* InLauncher, const class UAbilityComponentBase* InTarget, const TArray<struct FParamInfo>& Params_0, const struct FPreDamageResultData& PreDamageData, int32 InSkillLevel, const class UModifier* InModifier) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ReturnAttributeProductValue_C", "CaclValue");

	Params::ReturnAttributeProductValue_C_CaclValue Parms{};

	Parms.InLauncher = InLauncher;
	Parms.InTarget = InTarget;
	Parms.Params_0 = std::move(Params_0);
	Parms.PreDamageData = std::move(PreDamageData);
	Parms.InSkillLevel = InSkillLevel;
	Parms.InModifier = InModifier;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

