#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SelfCheck_IsInSpecializationSkillBlock

#include "Basic.hpp"

#include "SelfCheck_IsInSpecializationSkillBlock_classes.hpp"
#include "SelfCheck_IsInSpecializationSkillBlock_parameters.hpp"


namespace SDK
{

// Function SelfCheck_IsInSpecializationSkillBlock.SelfCheck_IsInSpecializationSkillBlock_C.K2_CheckCondition
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilityComponentBase*            InCurLauncher                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AGameCharacter*                   InCurLauncherChara                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool USelfCheck_IsInSpecializationSkillBlock_C::K2_CheckCondition(class UAbilityComponentBase* InCurLauncher, class AGameCharacter* InCurLauncherChara)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SelfCheck_IsInSpecializationSkillBlock_C", "K2_CheckCondition");

	Params::SelfCheck_IsInSpecializationSkillBlock_C_K2_CheckCondition Parms{};

	Parms.InCurLauncher = InCurLauncher;
	Parms.InCurLauncherChara = InCurLauncherChara;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SelfCheck_IsInSpecializationSkillBlock.SelfCheck_IsInSpecializationSkillBlock_C.K2_InitCondition
// (Event, Public, BlueprintEvent)

void USelfCheck_IsInSpecializationSkillBlock_C::K2_InitCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SelfCheck_IsInSpecializationSkillBlock_C", "K2_InitCondition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SelfCheck_IsInSpecializationSkillBlock.SelfCheck_IsInSpecializationSkillBlock_C.ExecuteUbergraph_SelfCheck_IsInSpecializationSkillBlock
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USelfCheck_IsInSpecializationSkillBlock_C::ExecuteUbergraph_SelfCheck_IsInSpecializationSkillBlock(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SelfCheck_IsInSpecializationSkillBlock_C", "ExecuteUbergraph_SelfCheck_IsInSpecializationSkillBlock");

	Params::SelfCheck_IsInSpecializationSkillBlock_C_ExecuteUbergraph_SelfCheck_IsInSpecializationSkillBlock Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

