#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shake_Wp06_Boom_01

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Shake_Wp06_Boom_01.Shake_Wp06_Boom_01_C
// 0x0000 (0x0180 - 0x0180)
class UShake_Wp06_Boom_01_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Shake_Wp06_Boom_01_C">();
	}
	static class UShake_Wp06_Boom_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShake_Wp06_Boom_01_C>();
	}
};
static_assert(alignof(UShake_Wp06_Boom_01_C) == 0x000010, "Wrong alignment on UShake_Wp06_Boom_01_C");
static_assert(sizeof(UShake_Wp06_Boom_01_C) == 0x000180, "Wrong size on UShake_Wp06_Boom_01_C");

}

