#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkillIntroControlEvent

#include "Basic.hpp"

#include "SkillIntroControlEvent_classes.hpp"
#include "SkillIntroControlEvent_parameters.hpp"


namespace SDK
{

// LuaFunction SkillIntroControlEvent.SkillIntroControlEvent_C.OnTrigger
// (Native, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

bool USkillIntroControlEvent_C::OnTrigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SkillIntroControlEvent_C", "OnTrigger");

	Params::SkillIntroControlEvent_C_OnTrigger Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SkillIntroControlEvent.SkillIntroControlEvent_C.GetSpecialStaticDescription
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString USkillIntroControlEvent_C::GetSpecialStaticDescription() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SkillIntroControlEvent_C", "GetSpecialStaticDescription");

	Params::SkillIntroControlEvent_C_GetSpecialStaticDescription Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SkillIntroControlEvent.SkillIntroControlEvent_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString USkillIntroControlEvent_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SkillIntroControlEvent_C", "GetModuleName");

	Params::SkillIntroControlEvent_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

