#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_Boss_101

#include "Basic.hpp"

#include "SM_Boss_101_classes.hpp"
#include "SM_Boss_101_parameters.hpp"


namespace SDK
{

// Function SM_Boss_101.SM_Boss_101_C.ExecuteUbergraph_SM_Boss_101
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USM_Boss_101_C::ExecuteUbergraph_SM_Boss_101(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "ExecuteUbergraph_SM_Boss_101");

	Params::SM_Boss_101_C_ExecuteUbergraph_SM_Boss_101 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_26()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_25()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_24()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_23()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_22()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_21()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_20()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_19()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_18()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_17()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_16()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_15()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_14()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_13()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_12()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_11()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_10()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SM_Boss_101.SM_Boss_101_C.SM_Boss_101.SM_Boss_101_C
// (BlueprintEvent)

void USM_Boss_101_C::Func_SM_Boss_101_SM_Boss_101_C_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_Boss_101_C", "SM_Boss_101.SM_Boss_101_C");

	UObject::ProcessEvent(Func, nullptr);
}

}

