#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SubWeaponBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function SubWeaponBase.SubWeaponBase_C.ReceiveShootBullet
// 0x0020 (0x0020 - 0x0000)
struct SubWeaponBase_C_ReceiveShootBullet final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsInSkill_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ReceiveShootBullet_ReturnValue;           // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetGameAnimInstance_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameCharacterAnimInstance*             K2Node_DynamicCast_AsGame_Character_Anim_Instance; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_SubWeaponBase_C_ReceiveShootBullet;

// Function SubWeaponBase.SubWeaponBase_C.ReceiveStartReload
// 0x0002 (0x0002 - 0x0000)
struct SubWeaponBase_C_ReceiveStartReload final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CallOwnerSMReceiveStartReload_ReturnValue; // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_SubWeaponBase_C_ReceiveStartReload;

// Function SubWeaponBase.SubWeaponBase_C.ReceiveStopFire
// 0x0008 (0x0008 - 0x0000)
struct SubWeaponBase_C_ReceiveStopFire final
{
public:
	int32                                         InStartSkillID;                                    // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_SubWeaponBase_C_ReceiveStopFire;

// Function SubWeaponBase.SubWeaponBase_C.ReceiveBreakFire
// 0x0004 (0x0004 - 0x0000)
struct SubWeaponBase_C_ReceiveBreakFire final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetCurrentStateId_ReturnValue;            // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_SubWeaponBase_C_ReceiveBreakFire;

}

