#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TDRandomBuff_137

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TDRandomBuff_137.TDRandomBuff_137_C
// 0x0000 (0x0150 - 0x0150)
class UTDRandomBuff_137_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TDRandomBuff_137_C">();
	}
	static class UTDRandomBuff_137_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTDRandomBuff_137_C>();
	}
};
static_assert(alignof(UTDRandomBuff_137_C) == 0x000008, "Wrong alignment on UTDRandomBuff_137_C");
static_assert(sizeof(UTDRandomBuff_137_C) == 0x000150, "Wrong size on UTDRandomBuff_137_C");

}

