#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tools_fun

#include "Basic.hpp"

#include "CollisionType_Enum_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tools_fun.Tools_fun_C
// 0x0000 (0x0028 - 0x0028)
class UTools_fun_C final : public UBlueprintFunctionLibrary
{
public:
	static void RotationDistanceSpline(bool FlipMesh, bool RottationWithSpline, bool ScaleWithSpline, class USplineMeshComponent* SplineMeshComponent, class USplineComponent* Spline, int32 PointIndex, float Distance, class UObject* __WorldContext);
	static void RotationWithSplinePoint(bool FlipMesh, bool RottationWithSpline, bool ScaleWithSpline, class USplineMeshComponent* SplineMeshComponent, class USplineComponent* Spline, int32 PointIndex, class UObject* __WorldContext);
	static void Initialize_the_fog(class UObject* __WorldContext);
	static void InShadow(class UPrimitiveComponent* __, class UMaterialInterface* __P_, float Shadow, class UObject* __WorldContext);
	static void CollisionType(ECollisionType_Enum CollisionType_0, class UObject* __WorldContext, class FName* TypeName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Tools_fun_C">();
	}
	static class UTools_fun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTools_fun_C>();
	}
};
static_assert(alignof(UTools_fun_C) == 0x000008, "Wrong alignment on UTools_fun_C");
static_assert(sizeof(UTools_fun_C) == 0x000028, "Wrong size on UTools_fun_C");

}

