#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trap001_LowHealth

#include "Basic.hpp"

#include "Game_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Trap001_LowHealth.Trap001_LowHealth_C
// 0x0018 (0x0040 - 0x0028)
class UTrap001_LowHealth_C final : public UCanInteractActor_Event
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0028(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   One;                                               // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Two;                                               // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Execute_Server(class AActor* InteractPlayer, class AActor* InteractActor);
	void ExecuteUbergraph_Trap001_LowHealth(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Trap001_LowHealth_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Trap001_LowHealth_C")
	}
	static class UTrap001_LowHealth_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTrap001_LowHealth_C>();
	}
};
DUMPER7_ASSERTS_UTrap001_LowHealth_C;

}

