#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TreasureBoxBase

#include "Basic.hpp"

#include "TreasureBoxBase_classes.hpp"
#include "TreasureBoxBase_parameters.hpp"


namespace SDK
{

// Function TreasureBoxBase.TreasureBoxBase_C.ExecuteUbergraph_TreasureBoxBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::ExecuteUbergraph_TreasureBoxBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "ExecuteUbergraph_TreasureBoxBase");

	Params::TreasureBoxBase_C_ExecuteUbergraph_TreasureBoxBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TreasureBoxBase.TreasureBoxBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ATreasureBoxBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.OnActive_Change
// (Event, Protected, BlueprintEvent)

void ATreasureBoxBase_C::OnActive_Change()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "OnActive_Change");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.OnActive_Client
// (Event, Protected, BlueprintEvent)

void ATreasureBoxBase_C::OnActive_Client()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "OnActive_Client");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.ReceiveEndPlay__Overridden
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::ReceiveEndPlay__Overridden(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "ReceiveEndPlay__Overridden");

	Params::TreasureBoxBase_C_ReceiveEndPlay__Overridden Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TreasureBoxBase.TreasureBoxBase_C.Client_OnStopInteracted
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AGamePlayer*                      Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::Client_OnStopInteracted(class AGamePlayer* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "Client_OnStopInteracted");

	Params::TreasureBoxBase_C_Client_OnStopInteracted Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TreasureBoxBase.TreasureBoxBase_C.Client_OnFinish
// (Event, Protected, BlueprintEvent)

void ATreasureBoxBase_C::Client_OnFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "Client_OnFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.Interact End
// (BlueprintCallable, BlueprintEvent)

void ATreasureBoxBase_C::Interact_End()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "Interact End");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.StopInteract
// (Event, Public, BlueprintEvent)

void ATreasureBoxBase_C::StopInteract()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "StopInteract");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "ReceiveTick");

	Params::TreasureBoxBase_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TreasureBoxBase.TreasureBoxBase_C.Server_OnFinish
// (Event, Protected, BlueprintEvent)

void ATreasureBoxBase_C::Server_OnFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "Server_OnFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.Server_OnInteracting
// (Event, Protected, BlueprintEvent)

void ATreasureBoxBase_C::Server_OnInteracting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "Server_OnInteracting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.Client_OnInteracting
// (Event, Protected, BlueprintEvent)

void ATreasureBoxBase_C::Client_OnInteracting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "Client_OnInteracting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.GetUMG
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class Ubox_tag_component_C*             UMG                                                    (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::GetUMG(class Ubox_tag_component_C** UMG)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "GetUMG");

	Params::TreasureBoxBase_C_GetUMG Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (UMG != nullptr)
		*UMG = Parms.UMG;
}


// Function TreasureBoxBase.TreasureBoxBase_C.BoxOpenFinish__Overridden
// (Public, BlueprintCallable, BlueprintEvent)

void ATreasureBoxBase_C::BoxOpenFinish__Overridden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "BoxOpenFinish__Overridden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.GetInteractionWidgetLua__Overridden
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::GetInteractionWidgetLua__Overridden(class UUserWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "GetInteractionWidgetLua__Overridden");

	Params::TreasureBoxBase_C_GetInteractionWidgetLua__Overridden Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


// Function TreasureBoxBase.TreasureBoxBase_C.GetInteractionWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUw_task_interaction_progress_C*  Interaction                                            (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::GetInteractionWidget(class UUw_task_interaction_progress_C** Interaction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "GetInteractionWidget");

	Params::TreasureBoxBase_C_GetInteractionWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Interaction != nullptr)
		*Interaction = Parms.Interaction;
}


// Function TreasureBoxBase.TreasureBoxBase_C.Stop Interaction
// (Public, BlueprintCallable, BlueprintEvent)

void ATreasureBoxBase_C::Stop_Interaction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "Stop Interaction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TreasureBoxBase.TreasureBoxBase_C.TriggerHandle__Overridden
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsBeginOverlap                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::TriggerHandle__Overridden(bool bIsBeginOverlap, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "TriggerHandle__Overridden");

	Params::TreasureBoxBase_C_TriggerHandle__Overridden Parms{};

	Parms.bIsBeginOverlap = bIsBeginOverlap;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TreasureBoxBase.TreasureBoxBase_C.InInteracting
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInteracting                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ATreasureBoxBase_C::InInteracting(bool* bInteracting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "InInteracting");

	Params::TreasureBoxBase_C_InInteracting Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bInteracting != nullptr)
		*bInteracting = Parms.bInteracting;
}


// Function TreasureBoxBase.TreasureBoxBase_C.ClientStopInteracton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGamePlayer*                      Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::ClientStopInteracton(class AGamePlayer* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "ClientStopInteracton");

	Params::TreasureBoxBase_C_ClientStopInteracton Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TreasureBoxBase.TreasureBoxBase_C.OnActiveChange__Overridden
// (Public, BlueprintCallable, BlueprintEvent)

void ATreasureBoxBase_C::OnActiveChange__Overridden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "OnActiveChange__Overridden");

	UObject::ProcessEvent(Func, nullptr);
}


// LuaFunction TreasureBoxBase.TreasureBoxBase_C.GetInteractionWidgetLua
// (Native, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::GetInteractionWidgetLua(class UUserWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "GetInteractionWidgetLua");

	Params::TreasureBoxBase_C_GetInteractionWidgetLua Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


// LuaFunction TreasureBoxBase.TreasureBoxBase_C.BoxOpenFinish
// (Native, Public, BlueprintCallable, BlueprintEvent)

void ATreasureBoxBase_C::BoxOpenFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "BoxOpenFinish");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// LuaFunction TreasureBoxBase.TreasureBoxBase_C.TriggerHandle
// (Native, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsBeginOverlap                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::TriggerHandle(bool bIsBeginOverlap, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "TriggerHandle");

	Params::TreasureBoxBase_C_TriggerHandle Parms{};

	Parms.bIsBeginOverlap = bIsBeginOverlap;
	Parms.OtherActor = OtherActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// LuaFunction TreasureBoxBase.TreasureBoxBase_C.OnActiveChange
// (Native, Public, BlueprintCallable, BlueprintEvent)

void ATreasureBoxBase_C::OnActiveChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "OnActiveChange");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// LuaFunction TreasureBoxBase.TreasureBoxBase_C.ReceiveEndPlay
// (Native, Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATreasureBoxBase_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "ReceiveEndPlay");

	Params::TreasureBoxBase_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// LuaFunction TreasureBoxBase.TreasureBoxBase_C.OnTrigger_Client
// (Native, Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsBeginOverlap                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// class AActor*                           OtherActor                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ATreasureBoxBase_C::OnTrigger_Client(bool bIsBeginOverlap, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "OnTrigger_Client");

	Params::TreasureBoxBase_C_OnTrigger_Client Parms{};

	Parms.bIsBeginOverlap = bIsBeginOverlap;
	Parms.OtherActor = OtherActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TreasureBoxBase.TreasureBoxBase_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ATreasureBoxBase_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TreasureBoxBase_C", "GetModuleName");

	Params::TreasureBoxBase_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

