#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_armor_subitem

#include "Basic.hpp"


namespace SDK::Params
{

// Function uw_armor_subitem.uw_armor_subitem_C.ExecuteUbergraph_uw_armor_subitem
// 0x0014 (0x0014 - 0x0000)
struct uw_armor_subitem_C_ExecuteUbergraph_uw_armor_subitem final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
};
DUMPER7_ASSERTS_uw_armor_subitem_C_ExecuteUbergraph_uw_armor_subitem;

// Function uw_armor_subitem.uw_armor_subitem_C.Play
// 0x0008 (0x0008 - 0x0000)
struct uw_armor_subitem_C_Play final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_uw_armor_subitem_C_Play;

}

