#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_armor_subitem2

#include "Basic.hpp"

#include "uw_armor_subitem2_classes.hpp"
#include "uw_armor_subitem2_parameters.hpp"


namespace SDK
{

// Function uw_armor_subitem2.uw_armor_subitem2_C.ExecuteUbergraph_uw_armor_subitem2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uuw_armor_subitem2_C::ExecuteUbergraph_uw_armor_subitem2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_armor_subitem2_C", "ExecuteUbergraph_uw_armor_subitem2");

	Params::uw_armor_subitem2_C_ExecuteUbergraph_uw_armor_subitem2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_armor_subitem2.uw_armor_subitem2_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)

void Uuw_armor_subitem2_C::CustomEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_armor_subitem2_C", "CustomEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function uw_armor_subitem2.uw_armor_subitem2_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void Uuw_armor_subitem2_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_armor_subitem2_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function uw_armor_subitem2.uw_armor_subitem2_C.Play
// (Public, BlueprintCallable, BlueprintEvent)

void Uuw_armor_subitem2_C::Play()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_armor_subitem2_C", "Play");

	UObject::ProcessEvent(Func, nullptr);
}

}

