#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_fight_turret

#include "Basic.hpp"

#include "uw_fight_turret_classes.hpp"
#include "uw_fight_turret_parameters.hpp"


namespace SDK
{

// LuaFunction uw_fight_turret.uw_fight_turret_C.Construct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void Uuw_fight_turret_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_turret_C", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// LuaFunction uw_fight_turret.uw_fight_turret_C.Destruct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void Uuw_fight_turret_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_turret_C", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// LuaFunction uw_fight_turret.uw_fight_turret_C.OnConstruct
// (Native, Event, Public, BlueprintEvent)

void Uuw_fight_turret_C::OnConstruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_turret_C", "OnConstruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function uw_fight_turret.uw_fight_turret_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString Uuw_fight_turret_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_turret_C", "GetModuleName");

	Params::uw_fight_turret_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

