#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Uw_fight_direction_maptarget

#include "Basic.hpp"

#include "Uw_fight_direction_maptarget_classes.hpp"
#include "Uw_fight_direction_maptarget_parameters.hpp"


namespace SDK
{

// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.SequenceEvent__ENTRYPOINTuw_fight_direction_maptarget_0
// (Public, BlueprintCallable, BlueprintEvent)

void UUw_fight_direction_maptarget_C::SequenceEvent__ENTRYPOINTuw_fight_direction_maptarget_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "SequenceEvent__ENTRYPOINTuw_fight_direction_maptarget_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.StartLoop
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Name_0                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    HasAppear                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUw_fight_direction_maptarget_C::StartLoop(const class FName Name_0, bool HasAppear)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "StartLoop");

	Params::Uw_fight_direction_maptarget_C_StartLoop Parms{};

	Parms.Name_0 = Name_0;
	Parms.HasAppear = HasAppear;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.SetDefendTargetPercent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUw_fight_direction_maptarget_C::SetDefendTargetPercent(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "SetDefendTargetPercent");

	Params::Uw_fight_direction_maptarget_C_SetDefendTargetPercent Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.OnVisibilityChanged_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUw_fight_direction_maptarget_C::OnVisibilityChanged_Event_0(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "OnVisibilityChanged_Event_0");

	Params::Uw_fight_direction_maptarget_C_OnVisibilityChanged_Event_0 Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.PlayDieAnim
// (Event, Public, BlueprintEvent)

void UUw_fight_direction_maptarget_C::PlayDieAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "PlayDieAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.AppearFinish
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUw_fight_direction_maptarget_C::AppearFinish(class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "AppearFinish");

	Params::Uw_fight_direction_maptarget_C_AppearFinish Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.OnAnimationFinished
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUw_fight_direction_maptarget_C::OnAnimationFinished(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "OnAnimationFinished");

	Params::Uw_fight_direction_maptarget_C_OnAnimationFinished Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.PlayTypeAnim
// (Event, Public, BlueprintEvent)

void UUw_fight_direction_maptarget_C::PlayTypeAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "PlayTypeAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.K2_OnCustomUmgAnimFinished
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             AnimName                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUw_fight_direction_maptarget_C::K2_OnCustomUmgAnimFinished(const class FName& AnimName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "K2_OnCustomUmgAnimFinished");

	Params::Uw_fight_direction_maptarget_C_K2_OnCustomUmgAnimFinished Parms{};

	Parms.AnimName = AnimName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_direction_maptarget.uw_fight_direction_maptarget_C.ExecuteUbergraph_uw_fight_direction_maptarget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUw_fight_direction_maptarget_C::ExecuteUbergraph_uw_fight_direction_maptarget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_direction_maptarget_C", "ExecuteUbergraph_uw_fight_direction_maptarget");

	Params::Uw_fight_direction_maptarget_C_ExecuteUbergraph_uw_fight_direction_maptarget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

