#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_fight_ShowBunkerState

#include "Basic.hpp"


namespace SDK::Params
{

// LuaFunction uw_fight_ShowBunkerState.uw_fight_ShowBunkerState_C.K2_OnUpdate
// 0x0004 (0x0004 - 0x0000)
struct uw_fight_ShowBunkerState_C_K2_OnUpdate final
{
public:
	float                                         InDeltaTime;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_uw_fight_ShowBunkerState_C_K2_OnUpdate;

// Function uw_fight_ShowBunkerState.uw_fight_ShowBunkerState_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct uw_fight_ShowBunkerState_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_uw_fight_ShowBunkerState_C_GetModuleName;

}

