#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_fight_injured_subitem1

#include "Basic.hpp"

#include "uw_fight_injured_subitem1_classes.hpp"
#include "uw_fight_injured_subitem1_parameters.hpp"


namespace SDK
{

// Function uw_fight_injured_subitem1.uw_fight_injured_subitem1_C.ExecuteUbergraph_uw_fight_injured_subitem1
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uuw_fight_injured_subitem1_C::ExecuteUbergraph_uw_fight_injured_subitem1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_injured_subitem1_C", "ExecuteUbergraph_uw_fight_injured_subitem1");

	Params::uw_fight_injured_subitem1_C_ExecuteUbergraph_uw_fight_injured_subitem1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_injured_subitem1.uw_fight_injured_subitem1_C.K2_OnCustomUmgAnimFinished
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      AnimName                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uuw_fight_injured_subitem1_C::K2_OnCustomUmgAnimFinished(const class FName& AnimName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_injured_subitem1_C", "K2_OnCustomUmgAnimFinished");

	Params::uw_fight_injured_subitem1_C_K2_OnCustomUmgAnimFinished Parms{};

	Parms.AnimName = AnimName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_fight_injured_subitem1.uw_fight_injured_subitem1_C.Play
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsBigDamage                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uuw_fight_injured_subitem1_C::Play(bool IsBigDamage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_injured_subitem1_C", "Play");

	Params::uw_fight_injured_subitem1_C_Play Parms{};

	Parms.IsBigDamage = IsBigDamage;

	UObject::ProcessEvent(Func, &Parms);
}

}

