#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_fight_crosshair_panel

#include "Basic.hpp"

#include "uw_fight_crosshair_panel_classes.hpp"
#include "uw_fight_crosshair_panel_parameters.hpp"


namespace SDK
{

// LuaFunction uw_fight_crosshair_panel.uw_fight_crosshair_panel_C.InitCrossHair
// (Native, Event, Public, HasDefaults, BlueprintEvent)
// Parameters:
// const struct FSoftClassPath&            CrossPath                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FSoftClassPath&            AmmunitionPath                                         (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void Uuw_fight_crosshair_panel_C::InitCrossHair(const struct FSoftClassPath& CrossPath, const struct FSoftClassPath& AmmunitionPath)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_crosshair_panel_C", "InitCrossHair");

	Params::uw_fight_crosshair_panel_C_InitCrossHair Parms{};

	Parms.CrossPath = std::move(CrossPath);
	Parms.AmmunitionPath = std::move(AmmunitionPath);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// LuaFunction uw_fight_crosshair_panel.uw_fight_crosshair_panel_C.Construct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void Uuw_fight_crosshair_panel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_crosshair_panel_C", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// LuaFunction uw_fight_crosshair_panel.uw_fight_crosshair_panel_C.K2_OnUpdate
// (Native, Event, Public, BlueprintEvent)
// Parameters:
// float                                   InDeltaTime                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void Uuw_fight_crosshair_panel_C::K2_OnUpdate(float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_crosshair_panel_C", "K2_OnUpdate");

	Params::uw_fight_crosshair_panel_C_K2_OnUpdate Parms{};

	Parms.InDeltaTime = InDeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// LuaFunction uw_fight_crosshair_panel.uw_fight_crosshair_panel_C.Destruct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void Uuw_fight_crosshair_panel_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_crosshair_panel_C", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function uw_fight_crosshair_panel.uw_fight_crosshair_panel_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString Uuw_fight_crosshair_panel_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_fight_crosshair_panel_C", "GetModuleName");

	Params::uw_fight_crosshair_panel_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

