#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Uw_fight_level_star

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Game_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass uw_fight_level_star.uw_fight_level_star_C
// 0x0010 (0x03C0 - 0x03B0)
class UUw_fight_level_star_C final : public ULuaWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCustListView*                          ListStar;                                          // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct__Overridden();
	void Destruct__Overridden();
	void ExecuteUbergraph_uw_fight_level_star(int32 EntryPoint);
	void Construct();
	void OnConstruct();
	void Destruct();

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"uw_fight_level_star_C">();
	}
	static class UUw_fight_level_star_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUw_fight_level_star_C>();
	}
};
static_assert(alignof(UUw_fight_level_star_C) == 0x000008, "Wrong alignment on UUw_fight_level_star_C");
static_assert(sizeof(UUw_fight_level_star_C) == 0x0003C0, "Wrong size on UUw_fight_level_star_C");
static_assert(offsetof(UUw_fight_level_star_C, UberGraphFrame) == 0x0003B0, "Member 'UUw_fight_level_star_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUw_fight_level_star_C, ListStar) == 0x0003B8, "Member 'UUw_fight_level_star_C::ListStar' has a wrong offset!");

}

