#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WildHuntingComponent

#include "Basic.hpp"

#include "WildHuntingComponent_classes.hpp"
#include "WildHuntingComponent_parameters.hpp"


namespace SDK
{

// Function WildHuntingComponent.WildHuntingComponent_C.SetAttribute
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilityComponentBase*            InOwner                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ChangeValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWildHuntingComponent_C::SetAttribute(class UAbilityComponentBase* InOwner, float ChangeValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WildHuntingComponent_C", "SetAttribute");

	Params::WildHuntingComponent_C_SetAttribute Parms{};

	Parms.InOwner = InOwner;
	Parms.ChangeValue = ChangeValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WildHuntingComponent.WildHuntingComponent_C.K2_ReceiveTick
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAbilityComponentBase*      InOwner                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWildHuntingComponent_C::K2_ReceiveTick(float DeltaSeconds, const class UAbilityComponentBase* InOwner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WildHuntingComponent_C", "K2_ReceiveTick");

	Params::WildHuntingComponent_C_K2_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;
	Parms.InOwner = InOwner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WildHuntingComponent.WildHuntingComponent_C.ExecuteUbergraph_WildHuntingComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWildHuntingComponent_C::ExecuteUbergraph_WildHuntingComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WildHuntingComponent_C", "ExecuteUbergraph_WildHuntingComponent");

	Params::WildHuntingComponent_C_ExecuteUbergraph_WildHuntingComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

